mysql:
  database: <%= ENV['db_name'] %>
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>
  host: <%= ENV['db_host'] %>

tables:
  review:
    author:
    email:

  customer:
    firstname:
    lastname:
    email:
    telephone:

  order:
    firstname:
    lastname:
    email:
    telephone:
